/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lk_j2c2_MyFunction */

#ifndef _Included_com_lk_j2c2_MyFunction
#define _Included_com_lk_j2c2_MyFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lk_j2c2_MyFunction
 * Method:    apply
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_lk_j2c2_MyFunction_apply
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_lk_j2c2_MyFunction
 * Method:    printf
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lk_j2c2_MyFunction_printf
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
